### ISSUE TITLE
Failed login

### ISSUE THREAD

**Issue by coticj** [handyman5/pyamazonclouddrive-clone#1]
Im trying to login using this, but i get the following error:

Logining to Amazon.com ... Traceback (most recent call last):
  File "./acdmkdir.py", line 165, in <module>
    main()
  File "./acdmkdir.py", line 120, in main
    elif not session.is_valid():
AttributeError: 'Session' object has no attribute 'is_valid'

I'm running it with: 

./acdmkdir.py -e something@something.com -p PASSWORD -s ~/.acdsession somewhere

**Comment by procmail** [comment]
Getting the exact same error.

**Comment by procmail** [comment]
Using acdlist.py, I get the same error message. But if I comment out the session.is_valid and session.is_logined checks, acdlist successfully shows the stuff on the Amazon Cloud Drive.

**Comment by handyman5** [comment]
Apparently there are changes in the upstream repo (removing those checks, for example) that I did not successfully copy into this repo. I will update it further.

**Comment by jurecotic** [comment]
Ok, I can confirm, that it works, if I remove that. But now I have a different problem. Acdlist lists completly different files than web client. And anything I upload through acd is not seen on the web and vice versa.

**Comment by handyman5** [comment]
See https://github.com/handyman5/acd_fuse/issues/10#issuecomment-90468203. I'm not sure what to do about this one.

**Comment by jurecotic** [comment]
Another login problem, which I'm having now:

pyacd.exception.PyAmazonCloudDriveError: PyAmazonCloudDriveError: You need to agree with license terms at web page: https://www.amazon.com/clouddrive

This happens when I try to upload a file through acdput.

**Comment by handyman5** [comment]
@jurecotic ... Have you tried visiting that web page and agreeing with the license terms? This seems like a pretty straightforward error.

**Comment by jurecotic** [comment]
Well yes, I did agree with the license terms when I created the account and logged in for the first time. When I visit the page I don't get any prompts or anything...

**Comment by handyman5** [comment]
Then I really have no idea, I'm afraid; I haven't seen that error myself.

**Comment by whsyu** [comment]
@jurecotic you can try to comment out that check in api.py
